// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7lYcywbLCuMAk2xaQBw9dvIjSD3kCRxE',
    appId: '1:979466727719:web:e3d01b931d13dd9ae8f902',
    messagingSenderId: '979466727719',
    projectId: 'ubixstar-assignment-app-acb4b',
    authDomain: 'ubixstar-assignment-app-acb4b.firebaseapp.com',
    storageBucket: 'ubixstar-assignment-app-acb4b.appspot.com',
    measurementId: 'G-FX4P4RB4KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMU9-LYlUhe82_trAczuxWFwCXY3uipRQ',
    appId: '1:979466727719:android:0883b470b0f01622e8f902',
    messagingSenderId: '979466727719',
    projectId: 'ubixstar-assignment-app-acb4b',
    storageBucket: 'ubixstar-assignment-app-acb4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3t5KFnoALoeDksqkxkHs_fYFYOelhCuU',
    appId: '1:979466727719:ios:3640b9269e57f1f0e8f902',
    messagingSenderId: '979466727719',
    projectId: 'ubixstar-assignment-app-acb4b',
    storageBucket: 'ubixstar-assignment-app-acb4b.appspot.com',
    iosBundleId: 'com.example.ubixstarAssignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3t5KFnoALoeDksqkxkHs_fYFYOelhCuU',
    appId: '1:979466727719:ios:3640b9269e57f1f0e8f902',
    messagingSenderId: '979466727719',
    projectId: 'ubixstar-assignment-app-acb4b',
    storageBucket: 'ubixstar-assignment-app-acb4b.appspot.com',
    iosBundleId: 'com.example.ubixstarAssignmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7lYcywbLCuMAk2xaQBw9dvIjSD3kCRxE',
    appId: '1:979466727719:web:8f93f891f0f9b6afe8f902',
    messagingSenderId: '979466727719',
    projectId: 'ubixstar-assignment-app-acb4b',
    authDomain: 'ubixstar-assignment-app-acb4b.firebaseapp.com',
    storageBucket: 'ubixstar-assignment-app-acb4b.appspot.com',
    measurementId: 'G-DMJLDZ79M1',
  );
}
